packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  '@apollo/protobufjs': true
  '@parcel/watcher': false
  '@swc/core': true
  core-js-pure: true
  esbuild: true
  sharp: true

onlyBuiltDependencies:
  - "@apollo/protobufjs"
  - "@swc/core"
  - core-js-pure
  - esbuild
  - sharp
